version: '3.8'
services:
  db:
    image: postgres:15
    container_name: javastock-postgres
    environment:
      POSTGRES_DB: javastocks
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    container_name: javastock-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: javastocks
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - mysql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  pgdata:
  mysqldata:
